language: c
os: linux
dist: bionic
sudo: required
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -y autoconf automake autotools-dev build-essential debhelper dh-autoreconf dpkg-dev gnome-doc-utils gnome-doc-utils imagemagick intltool libexiv2-dev libgtk2.0-dev libjpeg-dev liblcms2-dev liblircclient-dev liblua5.1-0-dev libtiff-dev libtool
script: (CFLAGS="-fPIC" ./autogen.sh) && make
