# SPDX-License-Identifier: GPL-2.0-or-later

unit_test_sources = files(
'collection-file-source.cc',
'editors.cc',
'filecache.cc',
'filedata/filedata.cc',
'filedata/filelist.cc',
'filedata/ref.cc',
'history-list.cc',
'image-load.cc',
'keyboard-shortcuts.cc',
'layout-image-navigation.cc',
'metadata-description.cc',
'pixbuf-util.cc',
'renderer-tiles.cc',
'trash.cc',
'ui-file-chooser.cc',
'ui-icon.cc',
'ui-tree-edit.cc',
'video-metadata.cc',
'view-dir.cc',
'view-file-list.cc')

project_sources += unit_test_sources
